name: 'dbt_olist_project'
profile: 'dbt_olist_project'
models:
  dbt_olist_project:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +tags: ["daily"]
      +materialized: view
    intermediate:
      +tags: ["hourly"]
      +materialized: view
    marts:
      +tags: ["daily"]
      +materialized: table
 
 
